### ISSUE TITLE
how to add/update email address not mailNickname?

### ISSUE THREAD

**Issue by ekhlascyblance** [Azure-Samples/active-directory-php-graphapi-web#11]
hi 
i want to add email of user
but not kbow tha name of the email 
For mail alias See Screenshot : [http://prntscr.com/gcu9ub](http://prntscr.com/gcu9ub)
 but what is for  email address for  user.

Thanks
Ikhlas

**Comment by TiagoBrenck** [comment]
This sample has been archived.
