### ISSUE TITLE
User update failed. Service returned error:Property 'mail' is read-only and cannot be set

### ISSUE THREAD

**Issue by ekhlascyblance** [Azure-Samples/active-directory-php-graphapi-web#12]
Hi 
error when update user
"User update failed. Service returned error:Property 'mail' is read-only and cannot be set. Please go back to Update User"

i want to know how to set Property 'mail' to read and write.

Thanks
Ikhlas

**Comment by kirill-kostenetskyi** [comment]
the same problem, does anybody have an answer ?

**Comment by TiagoBrenck** [comment]
This sample has been archived.
