### ISSUE TITLE
How to change/update password? 

### ISSUE THREAD

**Issue by ekhlascyblance** [Azure-Samples/active-directory-php-graphapi-web#13]
Hi 
I am php web developer.
i have setup azure graph api for add update azure user detail.
add update work great.
but when i update user with password 
it will give me error " Insufficient privileges to complete the operation ".
I give all the required permission.
is there any special permission for update password  of auzre user
because add with password works fine.
only issue occur in updating password.
Any help appreciated 

Thanks 
Ekhlas mullas

**Comment by TiagoBrenck** [comment]
This sample has been archived.
