### ISSUE TITLE
The PHP page is showing limited number of users and groups

### ISSUE THREAD

**Issue by nazihhaddad** [Azure-Samples/active-directory-php-graphapi-web#14]
Hi Folks,

Everything worked fine for me however the PHP pages DisplayUsers.php and DisplayGroups.php is not throwing all users and groups results but just a limited number.
Is there any way to change this to throw all Azure users or groups in the same page or in a pagination view?

Thank you,

**Comment by TiagoBrenck** [comment]
This sample has been archived.
