### ISSUE TITLE
Webmatrix is not supported since November 1, 2017

### ISSUE THREAD

**Issue by alldaemons** [Azure-Samples/active-directory-php-graphapi-web#15]
Last release of Webmatrix was (v7.1.1932.0) 12 October 2013. And, in 2016, Microsoft announced the discontinuation of WebMatrix in favour of Visual Studio Code with formal support ending on November 1, 2017.
So, how could I run a 

> Calling the Azure AD Graph API demo from a PHP web app ?

**Comment by TiagoBrenck** [comment]
This sample has been archived.
