### ISSUE TITLE
Can I get the Azure Active Directory template structure for users?

### ISSUE THREAD

**Issue by PrasadChinthala** [Azure-Samples/active-directory-php-graphapi-web#16]
I want to get the Azure Active Directory(AAD) template structure of users like cn, sn, uidNumber, mail & mobile. I have searched this repository files but could not find any one that provides the required data. I have already written code to get the users template structure for LDAP. Code is below :

`define('HOSTNAME','ldap://127.0.0.1');
$ldap_connection = ldap_connect(HOSTNAME,389) or die("Could not connect to ldap server");
ldap_set_option($ldap_connection, LDAP_OPT_PROTOCOL_VERSION, 3);
ldap_set_option($ldap_connection, LDAP_OPT_REFERRALS, 0);
$filter="(|(sn=*)(cn=admin))";
$sr=ldap_search($ldap_connection, $ldap_base_dn, $filter);
$entry = ldap_first_entry($ldap_connection, $sr);
$attrs = ldap_get_attributes($ldap_connection, $entry);
echo $attrs["count"] . " attributes held for this entry:<p>";
for ($i=0; $i < $attrs["count"]; $i++) {
    echo $attrs[$i] . "<br />";
}` 

**O/P :**
`10 attributes held for this entry:
cn
gidNumber
homeDirectory
sn
loginShell
objectClass
uidNumber
uid
mail
mobile`

Like I got LDAP template structure above, how can I get the AAD user's template structure? How can I achieve the same in AAD?

**Comment by TiagoBrenck** [comment]
This sample has been archived.
